#requires -Version 7.2

<#
.SYNOPSIS
    Detects programming projects and extracts relevant source files using a
    DriveArchive index.

.DESCRIPTION
    The script consumes index records in the following format:

        F<TAB>relative\file\path.ext
        D<TAB>relative\directory

    Projects are detected through repository and build-system markers such as:

        .git
        *.sln
        *.csproj
        package.json
        pyproject.toml
        Cargo.toml
        go.mod
        pom.xml
        CMakeLists.txt
        Makefile
        Dockerfile

    In Analyze mode, only reports are created.

    In Extract mode, relevant files are copied from SourceRoot into an isolated
    extraction directory. The source filesystem is never modified.

    Files not associated with a detected project are retained under
    "_Unclassified", preserving their original relative paths.

.NOTES
    Project detection is heuristic. No finite marker list can identify every
    historical or proprietary project layout.

    Review the generated manifests before publishing extracted files. Source
    trees may contain credentials, private keys, tokens, personal data,
    proprietary code, or confidential configuration.
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    # Index generated by DriveArchive.ps1.
    [Parameter(Mandatory)]
    [ValidateScript({ Test-Path -LiteralPath $_ -PathType Leaf })]
    [string]$IndexPath,

    # Original source corresponding to the index.
    # Required for Extract mode and used to validate source paths.
    [Parameter(Mandatory)]
    [ValidateScript({ Test-Path -LiteralPath $_ -PathType Container })]
    [string]$SourceRoot,

    # Parent directory in which the analysis/extraction run is created.
    [Parameter(Mandatory)]
    [string]$OutputRoot,

    [ValidateSet("Analyze", "Extract")]
    [string]$Mode = "Analyze",

    # Minimum accumulated marker score required for a detected project.
    [ValidateRange(1, 100)]
    [int]$MinimumProjectScore = 3,

    # Disable Write-Progress output.
    [switch]$NoProgress,

    # Replace an existing run directory with the same RunName.
    [switch]$Force,

    # Optional deterministic run-directory name.
    [ValidatePattern('^[^<>:"/\\|?*]+$')]
    [string]$RunName,

    # YAML-like exclusion file. The default location is exclusions.txt beside
    # this script.
    [string]$ExclusionsPath = (Join-Path $PSScriptRoot "exclusions.txt")
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

#region Configuration

$SourceExtensions = [System.Collections.Generic.HashSet[string]]::new(
    [System.StringComparer]::OrdinalIgnoreCase
)

@(
    # .NET and Microsoft ecosystems
    ".cs", ".csx", ".fs", ".fsx", ".fsi", ".vb", ".vbs",
    ".ps1", ".psm1", ".psd1", ".bat", ".cmd",

    # C, C++, Objective-C and related
    ".c", ".h", ".cc", ".hh", ".cpp", ".hpp", ".cxx", ".hxx",
    ".inl", ".ipp", ".m", ".mm",

    # JVM and Android
    ".java", ".kt", ".kts", ".groovy", ".scala", ".clj", ".cljs",
    ".cljc",

    # JavaScript and web
    ".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".vue", ".svelte",
    ".astro", ".html", ".htm", ".css", ".scss", ".sass", ".less",

    # Python and scientific computing
    ".py", ".pyw", ".pyi", ".pyx", ".pxd", ".pxi", ".ipynb",
    ".r", ".rmd", ".qmd", ".jl", ".m",

    # Systems and compiled languages
    ".rs", ".go", ".swift", ".dart", ".zig", ".nim", ".d", ".pas",
    ".pp", ".f", ".for", ".f77", ".f90", ".f95", ".f03", ".f08",
    ".asm", ".s", ".inc",

    # Scripting and dynamic languages
    ".rb", ".php", ".php3", ".php4", ".php5", ".phtml", ".pl",
    ".pm", ".t", ".lua", ".tcl", ".awk", ".sed", ".sh", ".bash",
    ".zsh", ".fish", ".ex", ".exs", ".erl", ".hrl", ".hs", ".lhs",
    ".ml", ".mli", ".fs",

    # Database, query and data languages
    ".sql", ".psql", ".graphql", ".gql", ".sparql", ".cypher",

    # Hardware, formal and scientific languages
    ".v", ".vh", ".sv", ".svh", ".vhd", ".vhdl", ".sol", ".wat",
    ".wast", ".tex", ".sty", ".cls",

    # Interface definitions and generators
    ".proto", ".thrift", ".avdl", ".avsc", ".idl", ".xsd", ".xslt",

    # Infrastructure as code
    ".tf", ".tfvars", ".hcl", ".bicep", ".nix",

    # Templates that commonly contain executable source
    ".ejs", ".hbs", ".handlebars", ".mustache", ".jinja",
    ".jinja2", ".twig", ".erb", ".razor", ".cshtml", ".vbhtml",

    # Legacy and specialist languages
    ".cob", ".cbl", ".ada", ".adb", ".ads", ".lisp", ".lsp",
    ".cl", ".scm", ".rkt", ".pro", ".prolog", ".forth", ".fth"
) | ForEach-Object {
    [void]$SourceExtensions.Add($_)
}

$RelevantFileNames = [System.Collections.Generic.HashSet[string]]::new(
    [System.StringComparer]::OrdinalIgnoreCase
)

@(
    # Generic repository metadata
    ".editorconfig",
    ".gitattributes",
    ".gitignore",
    ".gitmodules",
    ".dockerignore",
    ".npmignore",
    ".prettierignore",
    ".prettierrc",
    ".eslintrc",
    ".stylelintrc",
    ".clang-format",
    ".clang-tidy",

    # Containers and CI
    "Dockerfile",
    "docker-compose.yml",
    "docker-compose.yaml",
    "compose.yml",
    "compose.yaml",
    "Jenkinsfile",
    ".gitlab-ci.yml",
    ".gitlab-ci.yaml",
    "azure-pipelines.yml",
    "azure-pipelines.yaml",
    "appveyor.yml",

    # Build systems
    "Makefile",
    "GNUmakefile",
    "CMakeLists.txt",
    "meson.build",
    "meson_options.txt",
    "build.ninja",
    "WORKSPACE",
    "WORKSPACE.bazel",
    "BUILD",
    "BUILD.bazel",

    # JavaScript
    "package.json",
    "package-lock.json",
    "npm-shrinkwrap.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lock",
    "bun.lockb",
    "tsconfig.json",
    "jsconfig.json",
    "deno.json",
    "deno.jsonc",

    # Python
    "pyproject.toml",
    "setup.py",
    "setup.cfg",
    "requirements.txt",
    "requirements-dev.txt",
    "Pipfile",
    "Pipfile.lock",
    "poetry.lock",
    "tox.ini",
    "pytest.ini",
    "environment.yml",
    "environment.yaml",
    "conda.yml",
    "conda.yaml",

    # Rust, Go, Ruby, PHP, Elixir, Dart and Swift
    "Cargo.toml",
    "Cargo.lock",
    "go.mod",
    "go.sum",
    "Gemfile",
    "Gemfile.lock",
    "Rakefile",
    "composer.json",
    "composer.lock",
    "mix.exs",
    "mix.lock",
    "pubspec.yaml",
    "pubspec.lock",
    "Package.swift",

    # JVM
    "pom.xml",
    "build.gradle",
    "build.gradle.kts",
    "settings.gradle",
    "settings.gradle.kts",
    "gradle.properties",

    # .NET
    "Directory.Build.props",
    "Directory.Build.targets",
    "Directory.Packages.props",
    "global.json",
    "nuget.config",

    # Other ecosystems
    "project.clj",
    "deps.edn",
    "stack.yaml",
    "cabal.project",
    "rebar.config",
    "dune-project",
    "lakefile.lean",
    "lean-toolchain",

    # Safe environment templates only
    ".env.example",
    ".env.sample",
    ".env.template"
) | ForEach-Object {
    [void]$RelevantFileNames.Add($_)
}

# Exact marker names and their evidence weights.
$MarkerWeights = @{
    ".git"                    = 10
    "package.json"            = 6
    "pyproject.toml"          = 7
    "setup.py"                = 5
    "Cargo.toml"              = 8
    "go.mod"                  = 8
    "pom.xml"                 = 8
    "build.gradle"            = 7
    "build.gradle.kts"        = 7
    "settings.gradle"         = 7
    "settings.gradle.kts"     = 7
    "CMakeLists.txt"          = 6
    "Makefile"                = 3
    "GNUmakefile"             = 3
    "meson.build"             = 6
    "WORKSPACE"               = 6
    "WORKSPACE.bazel"         = 6
    "BUILD.bazel"             = 4
    "composer.json"           = 6
    "Gemfile"                 = 6
    "mix.exs"                 = 6
    "pubspec.yaml"            = 6
    "Package.swift"           = 7
    "project.clj"             = 6
    "deps.edn"                = 6
    "stack.yaml"              = 6
    "rebar.config"            = 6
    "dune-project"            = 6
    "Dockerfile"              = 3
    "docker-compose.yml"      = 4
    "docker-compose.yaml"     = 4
    "Jenkinsfile"             = 3
    ".gitlab-ci.yml"          = 3
    "azure-pipelines.yml"     = 3
    "Directory.Build.props"   = 4
    "Directory.Build.targets" = 4
}

$ExcludedDirectoryNames = [System.Collections.Generic.HashSet[string]]::new(
    [System.StringComparer]::OrdinalIgnoreCase
)

@(
    # Version-control internals
    ".git", ".svn", ".hg", "CVS",

    # Dependency directories
    "node_modules", "bower_components", "jspm_packages",
    "vendor", "packages", ".nuget",
    ".venv", "venv", "env", ".tox",
    "Pods", "Carthage",
    "target",

    # Build output
    "bin", "obj", "dist", "build", "out",
    "Debug", "Release", "x64", "x86",
    ".gradle", ".dart_tool", ".pub-cache",
    ".next", ".nuxt", ".svelte-kit", ".angular",
    "coverage", ".coverage", "TestResults",

    # Caches and generated metadata
    "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache",
    ".cache", ".parcel-cache", ".turbo",
    ".idea", ".vs", ".vscode",
    ".ipynb_checkpoints",

    # macOS and operating-system metadata
    ".Trash", ".Trashes", "System Volume Information",
    '$RECYCLE.BIN'
) | ForEach-Object {
    [void]$ExcludedDirectoryNames.Add($_)
}

# Files excluded even when their extensions otherwise appear relevant.
$SensitiveFileNames = [System.Collections.Generic.HashSet[string]]::new(
    [System.StringComparer]::OrdinalIgnoreCase
)

@(
    ".env",
    ".env.local",
    ".env.production",
    ".env.development",
    ".npmrc",
    ".pypirc",
    "id_rsa",
    "id_dsa",
    "id_ecdsa",
    "id_ed25519",
    "credentials",
    "credentials.json",
    "secrets.json"
) | ForEach-Object {
    [void]$SensitiveFileNames.Add($_)
}

#endregion Configuration

#region Utility functions

function ConvertTo-NormalizedRelativePath {
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    $normalized = $Path.Replace("/", "\")
    $normalized = $normalized.TrimStart([char[]]@("\", "/"))

    if ([string]::IsNullOrWhiteSpace($normalized)) {
        return ""
    }

    $segments = $normalized.Split(
        [char[]]@("\", "/"),
        [System.StringSplitOptions]::RemoveEmptyEntries
    )

    if ($segments -contains "..") {
        throw "Unsafe relative path containing '..': '$Path'"
    }

    if ([System.IO.Path]::IsPathRooted($normalized)) {
        throw "Index contains a rooted path: '$Path'"
    }

    return [string]::Join("\", $segments)
}

function Get-RelativeParent {
    param(
        [Parameter(Mandatory)]
        [AllowEmptyString()]
        [string]$RelativePath
    )

    $position = $RelativePath.LastIndexOf("\")

    if ($position -lt 0) {
        return ""
    }

    return $RelativePath.Substring(0, $position)
}

function Get-RelativeLeaf {
    param(
        [Parameter(Mandatory)]
        [string]$RelativePath
    )

    $position = $RelativePath.LastIndexOf("\")

    if ($position -lt 0) {
        return $RelativePath
    }

    return $RelativePath.Substring($position + 1)
}

function Import-PathExclusions {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$Path
    )

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "Exclusion file does not exist: '$Path'"
    }

    $filenameParts = [System.Collections.Generic.HashSet[string]]::new(
        [System.StringComparer]::OrdinalIgnoreCase
    )

    $folderParts = [System.Collections.Generic.HashSet[string]]::new(
        [System.StringComparer]::OrdinalIgnoreCase
    )

    $currentSection = $null
    $lineNumber = 0

    foreach ($line in [System.IO.File]::ReadLines($Path)) {
        $lineNumber++
        $trimmedLine = $line.Trim()

        if (
            [string]::IsNullOrWhiteSpace($trimmedLine) -or
            $trimmedLine.StartsWith("#")
        ) {
            continue
        }

        # Accept both:
        #   - FilenameParts:
        # and:
        #   FilenameParts:
        if (
            $trimmedLine -match
            '^(?:-\s*)?(FilenameParts|FolderParts)\s*:\s*$'
        ) {
            $currentSection = $Matches[1]
            continue
        }

        if ($trimmedLine -notmatch '^-\s*(.+?)\s*$') {
            throw (
                "Invalid exclusions file syntax at line {0}: {1}" -f
                $lineNumber,
                $line
            )
        }

        if ($null -eq $currentSection) {
            throw (
                "Exclusion item declared before a section at line {0}: {1}" -f
                $lineNumber,
                $line
            )
        }

        $value = $Matches[1].Trim()

        # Permit simple single- or double-quoted values.
        if (
            $value.Length -ge 2 -and
            (
                (
                    $value.StartsWith('"') -and
                    $value.EndsWith('"')
                ) -or
                (
                    $value.StartsWith("'") -and
                    $value.EndsWith("'")
                )
            )
        ) {
            $value = $value.Substring(1, $value.Length - 2).Trim()
        }

        if ([string]::IsNullOrWhiteSpace($value)) {
            throw "Empty exclusion at line $lineNumber in '$Path'."
        }

        if ($value.IndexOfAny([char[]]@("\", "/")) -ge 0) {
            throw (
                "Exclusion values must be filename or folder-name parts, " +
                "not paths. Invalid value at line ${lineNumber}: '$value'"
            )
        }

        switch ($currentSection) {
            "FilenameParts" {
                [void]$filenameParts.Add($value)
            }

            "FolderParts" {
                [void]$folderParts.Add($value)
            }

            default {
                throw "Unsupported exclusion section '$currentSection'."
            }
        }
    }

    return [PSCustomObject]@{
        FilenameParts = [string[]]@(
            $filenameParts |
                Sort-Object
        )
        FolderParts = [string[]]@(
            $folderParts |
                Sort-Object
        )
    }
}

function Test-UserExcludedPath {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]$RelativePath,

        [Parameter(Mandatory)]
        [ValidateSet("F", "D")]
        [string]$RecordType,

        [string[]]$FilenameParts = @(),

        [string[]]$FolderParts = @()
    )

    # Filename exclusions apply only to file records and only to the leaf
    # filename, not to the complete path.
    if ($RecordType -eq "F" -and $FilenameParts.Count -gt 0) {
        $fileName = Get-RelativeLeaf -RelativePath $RelativePath

        foreach ($part in $FilenameParts) {
            if (
                $fileName.IndexOf(
                    $part,
                    [System.StringComparison]::OrdinalIgnoreCase
                ) -ge 0
            ) {
                return $true
            }
        }
    }

    if ($FolderParts.Count -eq 0) {
        return $false
    }

    # For files, inspect only the containing directory components.
    # For directories, inspect the directory itself and all its ancestors.
    $folderPath = if ($RecordType -eq "F") {
        Get-RelativeParent -RelativePath $RelativePath
    }
    else {
        $RelativePath
    }

    if ([string]::IsNullOrWhiteSpace($folderPath)) {
        return $false
    }

    foreach ($folderName in $folderPath.Split("\")) {
        foreach ($part in $FolderParts) {
            if (
                $folderName.IndexOf(
                    $part,
                    [System.StringComparison]::OrdinalIgnoreCase
                ) -ge 0
            ) {
                return $true
            }
        }
    }

    return $false
}

function Test-ExcludedPath {
    param(
        [Parameter(Mandatory)]
        [string]$RelativePath
    )

    foreach ($segment in $RelativePath.Split("\")) {
        if ($ExcludedDirectoryNames.Contains($segment)) {
            return $true
        }
    }

    return $false
}

function Get-MarkerWeight {
    param(
        [Parameter(Mandatory)]
        [string]$FileName
    )

    if ($MarkerWeights.ContainsKey($FileName)) {
        return [int]$MarkerWeights[$FileName]
    }

    $extension = [System.IO.Path]::GetExtension($FileName)

    switch -Regex ($extension) {
        '^\.(sln|slnx)$' {
            return 9
        }

        '^\.(csproj|fsproj|vbproj|vcxproj|sqlproj|wixproj|proj)$' {
            return 8
        }

        '^\.(xcodeproj|xcworkspace)$' {
            return 8
        }

        '^\.(cabal)$' {
            return 6
        }

        default {
            return 0
        }
    }
}

function Get-RelevantFileKind {
    param(
        [Parameter(Mandatory)]
        [string]$RelativePath
    )

    $fileName = Get-RelativeLeaf -RelativePath $RelativePath

    if ($SensitiveFileNames.Contains($fileName)) {
        return $null
    }

    if ($fileName -match '(?i)\.(pem|key|pfx|p12|jks|keystore)$') {
        return $null
    }

    $extension = [System.IO.Path]::GetExtension($fileName)

    if ($SourceExtensions.Contains($extension)) {
        return "Source"
    }

    if ((Get-MarkerWeight -FileName $fileName) -gt 0) {
        return "ProjectMarker"
    }

    if ($RelevantFileNames.Contains($fileName)) {
        return "ProjectMetadata"
    }

    if ($fileName -match '^(?i)(README|CHANGELOG|CHANGES|CONTRIBUTING|AUTHORS|NOTICE|COPYING|LICENSE)(\..+)?$') {
        return "Documentation"
    }

    if ($RelativePath -match '(?i)(^|\\)\.github\\workflows\\.+\.ya?ml$') {
        return "ContinuousIntegration"
    }

    if ($RelativePath -match '(?i)(^|\\)\.devcontainer\\.+$') {
        return "DevelopmentConfiguration"
    }

    return $null
}

function Add-ProjectEvidence {
    param(
        [Parameter(Mandatory)]
        [System.Collections.Generic.Dictionary[string, object]]$Candidates,

        [Parameter(Mandatory)]
        [AllowEmptyString()]
        [string]$ProjectRoot,

        [Parameter(Mandatory)]
        [string]$Evidence,

        [Parameter(Mandatory)]
        [int]$Weight
    )

    # A project marker in the root of the indexed source does not establish a
    # safe extraction boundary. Such files remain unclassified.
    if ([string]::IsNullOrWhiteSpace($ProjectRoot)) {
        return
    }

    if (-not $Candidates.ContainsKey($ProjectRoot)) {
        $Candidates[$ProjectRoot] = [PSCustomObject]@{
            Root = $ProjectRoot
            Score = 0
            Evidence = [System.Collections.Generic.HashSet[string]]::new(
                [System.StringComparer]::OrdinalIgnoreCase
            )
        }
    }

    $candidate = $Candidates[$ProjectRoot]

    if ($candidate.Evidence.Add($Evidence)) {
        $candidate.Score += $Weight
    }
}

function Get-StableShortHash {
    param(
        [Parameter(Mandatory)]
        [string]$Text
    )

    $bytes = [System.Text.Encoding]::UTF8.GetBytes($Text)
    $hash = [System.Security.Cryptography.SHA256]::HashData($bytes)

    return [System.Convert]::ToHexString($hash).Substring(0, 10).ToLowerInvariant()
}

function ConvertTo-SafeDirectoryName {
    param(
        [Parameter(Mandatory)]
        [string]$Name
    )

    $invalidCharacters = [System.IO.Path]::GetInvalidFileNameChars()

    foreach ($character in $invalidCharacters) {
        $Name = $Name.Replace($character, "_")
    }

    $Name = $Name.Trim().TrimEnd(".")

    if ([string]::IsNullOrWhiteSpace($Name)) {
        return "UnnamedProject"
    }

    if ($Name.Length -gt 80) {
        return $Name.Substring(0, 80)
    }

    return $Name
}

function Find-ContainingProjectRoot {
    param(
        [Parameter(Mandatory)]
        [string]$FileRelativePath,

        [Parameter(Mandatory)]
        [System.Collections.Generic.Dictionary[string, object]]$ProjectByRoot
    )

    $directory = Get-RelativeParent -RelativePath $FileRelativePath

    while (-not [string]::IsNullOrEmpty($directory)) {
        if ($ProjectByRoot.ContainsKey($directory)) {
            return $directory
        }

        $parent = Get-RelativeParent -RelativePath $directory

        if ($parent -eq $directory) {
            break
        }

        $directory = $parent
    }

    return $null
}

function ConvertTo-CsvField {
    param(
        [AllowNull()]
        [object]$Value
    )

    if ($null -eq $Value) {
        return '""'
    }

    $text = [string]$Value
    return '"' + $text.Replace('"', '""') + '"'
}

#endregion Utility functions

#region Load exclusions

$resolvedExclusionsPath = (
    Resolve-Path -LiteralPath $ExclusionsPath -ErrorAction Stop
).Path

$pathExclusions = Import-PathExclusions `
    -Path $resolvedExclusionsPath

Write-Verbose (
    "Loaded {0:N0} filename exclusions and {1:N0} folder exclusions " +
    "from '{2}'." -f
    $pathExclusions.FilenameParts.Count,
    $pathExclusions.FolderParts.Count,
    $resolvedExclusionsPath
)

#endregion Load exclusions

#region Initialize output

$resolvedIndexPath = (Resolve-Path -LiteralPath $IndexPath).Path
$resolvedSourceRoot = (Resolve-Path -LiteralPath $SourceRoot).Path.TrimEnd(
    [char[]]@("\", "/")
)

if (-not $RunName) {
    $RunName = "CodeDiscovery_{0:yyyyMMdd_HHmmss}" -f (Get-Date)
}

$runDirectory = Join-Path $OutputRoot $RunName
$extractionDirectory = Join-Path $runDirectory "ExtractedProjects"
$reportDirectory = Join-Path $runDirectory "Reports"

if (Test-Path -LiteralPath $runDirectory) {
    if (-not $Force) {
        throw "Run directory already exists: '$runDirectory'. Use -Force or another -RunName."
    }

    Remove-Item -LiteralPath $runDirectory -Recurse -Force
}

[void][System.IO.Directory]::CreateDirectory($reportDirectory)

if ($Mode -eq "Extract") {
    [void][System.IO.Directory]::CreateDirectory($extractionDirectory)
}

#endregion Initialize output

#region Read index and identify evidence

$projectCandidates =
    [System.Collections.Generic.Dictionary[string, object]]::new(
        [System.StringComparer]::OrdinalIgnoreCase
    )

$relevantFiles = [System.Collections.Generic.List[string]]::new()

$indexedFileCount = 0L
$indexedDirectoryCount = 0L
$excludedRecordCount = 0L
$userExcludedRecordCount = 0L
$relevantRecordCount = 0L
$invalidRecordCount = 0L

$reader = [System.IO.StreamReader]::new(
    $resolvedIndexPath,
    [System.Text.Encoding]::UTF8,
    $true,
    1MB
)

try {
    while (-not $reader.EndOfStream) {
        $line = $reader.ReadLine()

        if ([string]::IsNullOrWhiteSpace($line)) {
            continue
        }

        $separatorPosition = $line.IndexOf("`t")

        if ($separatorPosition -lt 1) {
            # DriveArchive headers and unrelated metadata are ignored.
            continue
        }

        $recordType = $line.Substring(0, $separatorPosition)
        $rawRelativePath = $line.Substring($separatorPosition + 1)

        if ($recordType -notin @("F", "D")) {
            continue
        }

        try {
            $relativePath = ConvertTo-NormalizedRelativePath `
                -Path $rawRelativePath
        }
        catch {
            $invalidRecordCount++
            Write-Warning $_.Exception.Message
            continue
        }

        if ([string]::IsNullOrWhiteSpace($relativePath)) {
            continue
        }

        # Apply user exclusions before directory-marker detection, project evidence
        # collection, source classification, or report generation.
        if (
            Test-UserExcludedPath `
                -RelativePath $relativePath `
                -RecordType $recordType `
                -FilenameParts $pathExclusions.FilenameParts `
                -FolderParts $pathExclusions.FolderParts
        ) {
            $userExcludedRecordCount++
            continue
        }

        if ($recordType -eq "D") {
            $indexedDirectoryCount++

            # Directory-based project markers must be processed before the
            # directory itself is excluded from file extraction.
            $directoryName = Get-RelativeLeaf -RelativePath $relativePath
            $directoryParent = Get-RelativeParent -RelativePath $relativePath

            if (
                $directoryName.Equals(
                    ".git",
                    [System.StringComparison]::OrdinalIgnoreCase
                )
            ) {
                Add-ProjectEvidence `
                    -Candidates $projectCandidates `
                    -ProjectRoot $directoryParent `
                    -Evidence ".git directory" `
                    -Weight 10
            }
            elseif (
                $directoryName -match
                '(?i)\.(xcodeproj|xcworkspace)$'
            ) {
                Add-ProjectEvidence `
                    -Candidates $projectCandidates `
                    -ProjectRoot $directoryParent `
                    -Evidence $directoryName `
                    -Weight 8
            }

            continue
        }

        $indexedFileCount++

        if (Test-ExcludedPath -RelativePath $relativePath) {
            $excludedRecordCount++
            continue
        }

        $fileName = Get-RelativeLeaf -RelativePath $relativePath
        $markerWeight = Get-MarkerWeight -FileName $fileName

        if ($markerWeight -gt 0) {
            $candidateRoot = Get-RelativeParent `
                -RelativePath $relativePath

            Add-ProjectEvidence `
                -Candidates $projectCandidates `
                -ProjectRoot $candidateRoot `
                -Evidence $fileName `
                -Weight $markerWeight
        }

        $kind = Get-RelevantFileKind -RelativePath $relativePath

        if ($null -ne $kind) {
            $relevantFiles.Add($relativePath)
            $relevantRecordCount++
        }

        if (
            -not $NoProgress -and
            ($indexedFileCount % 50000L) -eq 0
        ) {
            $statusFormat = (
            "{0:N0} files read | {1:N0} relevant | " +
            "{2:N0} excluded by rules | {3:N0} candidate roots"
        )

        $status = $statusFormat -f @(
            $indexedFileCount,
            $relevantRecordCount,
            $userExcludedRecordCount,
            $projectCandidates.Count
        )

            Write-Progress `
                -Id 20 `
                -Activity "Analyzing DriveArchive index" `
                -Status $status `
                -CurrentOperation $relativePath
        }
    }
}
finally {
    $reader.Dispose()

    if (-not $NoProgress) {
        Write-Progress `
            -Id 20 `
            -Activity "Analyzing DriveArchive index" `
            -Completed
    }
}

#endregion Read index and identify evidence

#region Select projects

$projectByRoot =
    [System.Collections.Generic.Dictionary[string, object]]::new(
        [System.StringComparer]::OrdinalIgnoreCase
    )

$projects = [System.Collections.Generic.List[object]]::new()

foreach ($candidate in $projectCandidates.Values) {
    if ($candidate.Score -lt $MinimumProjectScore) {
        continue
    }

    $leafName = Get-RelativeLeaf -RelativePath $candidate.Root
    $safeName = ConvertTo-SafeDirectoryName -Name $leafName
    $shortHash = Get-StableShortHash -Text $candidate.Root
    $destinationName = "{0}--{1}" -f $safeName, $shortHash

    $project = [PSCustomObject]@{
        Id = $shortHash
        Name = $leafName
        RelativeRoot = $candidate.Root
        Score = [int]$candidate.Score
        Evidence = @($candidate.Evidence | Sort-Object)
        DestinationName = $destinationName
        RelevantFileCount = 0L
        SourceFileCount = 0L
        MissingFileCount = 0L
        CopyErrorCount = 0L
    }

    $projectByRoot[$candidate.Root] = $project
    $projects.Add($project)
}

#endregion Select projects

#region Classify files

$unclassifiedRelevantCount = 0L
$unclassifiedSourceCount = 0L

foreach ($relativePath in $relevantFiles) {
    $projectRoot = Find-ContainingProjectRoot `
        -FileRelativePath $relativePath `
        -ProjectByRoot $projectByRoot

    $kind = Get-RelevantFileKind -RelativePath $relativePath

    if ($null -ne $projectRoot) {
        $project = $projectByRoot[$projectRoot]
        $project.RelevantFileCount++

        if ($kind -eq "Source") {
            $project.SourceFileCount++
        }
    }
    else {
        $unclassifiedRelevantCount++

        if ($kind -eq "Source") {
            $unclassifiedSourceCount++
        }
    }
}

#endregion Classify files

#region Write project report

$projectsCsvPath = Join-Path $reportDirectory "projects.csv"

$projects |
    Sort-Object RelativeRoot |
    Select-Object @(
        "Id"
        "Name"
        "RelativeRoot"
        "Score"
        "RelevantFileCount"
        "SourceFileCount"
        @{
            Name = "Evidence"
            Expression = { $_.Evidence -join "; " }
        }
        "DestinationName"
    ) |
    Export-Csv `
        -LiteralPath $projectsCsvPath `
        -NoTypeInformation `
        -Encoding utf8

#endregion Write project report

#region Extract or manifest files

$filesCsvPath = Join-Path $reportDirectory "files.csv"

$filesWriter = [System.IO.StreamWriter]::new(
    $filesCsvPath,
    $false,
    [System.Text.UTF8Encoding]::new($true),
    1MB
)

$createdDirectories = [System.Collections.Generic.HashSet[string]]::new(
    [System.StringComparer]::OrdinalIgnoreCase
)

$processedRelevantFiles = 0L
$copiedFileCount = 0L
$missingFileCount = 0L
$copyErrorCount = 0L

try {
    $filesWriter.WriteLine(
        '"SourceRelativePath","Kind","ProjectId","ProjectRoot",' +
        '"DestinationRelativePath","Status","Error"'
    )

    foreach ($relativePath in $relevantFiles) {
        $processedRelevantFiles++

        $kind = Get-RelevantFileKind -RelativePath $relativePath

        if ($null -eq $kind) {
            continue
        }

        $projectRoot = Find-ContainingProjectRoot `
            -FileRelativePath $relativePath `
            -ProjectByRoot $projectByRoot

        $projectId = ""
        $destinationRelativePath = ""
        $project = $null

        if ($null -ne $projectRoot) {
            $project = $projectByRoot[$projectRoot]
            $projectId = $project.Id

            $prefixLength = $projectRoot.Length

            if ($relativePath.Length -gt $prefixLength) {
                $insideProject = $relativePath.Substring(
                    $prefixLength
                ).TrimStart("\")
            }
            else {
                $insideProject = Get-RelativeLeaf `
                    -RelativePath $relativePath
            }

            $destinationRelativePath = Join-Path `
                $project.DestinationName `
                $insideProject
        }
        else {
            $destinationRelativePath = Join-Path `
                "_Unclassified" `
                $relativePath
        }

        $sourcePath = Join-Path $resolvedSourceRoot $relativePath
        $destinationPath = Join-Path `
            $extractionDirectory `
            $destinationRelativePath

        $status = "Analyzed"
        $errorText = ""

        if ($Mode -eq "Extract") {
            if (-not [System.IO.File]::Exists($sourcePath)) {
                $status = "Missing"
                $missingFileCount++

                if ($null -ne $project) {
                    $project.MissingFileCount++
                }
            }
            elseif (
                $PSCmdlet.ShouldProcess(
                    $sourcePath,
                    "Copy to '$destinationPath'"
                )
            ) {
                try {
                    $destinationParent = [System.IO.Path]::GetDirectoryName(
                        $destinationPath
                    )

                    if ($createdDirectories.Add($destinationParent)) {
                        [void][System.IO.Directory]::CreateDirectory(
                            $destinationParent
                        )
                    }

                    [System.IO.File]::Copy(
                        $sourcePath,
                        $destinationPath,
                        $true
                    )

                    # Preserve basic timestamps without copying ACLs,
                    # alternate data streams, or filesystem ownership.
                    $sourceInfo = [System.IO.FileInfo]::new($sourcePath)
                    $destinationInfo = [System.IO.FileInfo]::new(
                        $destinationPath
                    )

                    $destinationInfo.CreationTimeUtc =
                        $sourceInfo.CreationTimeUtc

                    $destinationInfo.LastWriteTimeUtc =
                        $sourceInfo.LastWriteTimeUtc

                    $status = "Copied"
                    $copiedFileCount++
                }
                catch {
                    $status = "CopyError"
                    $errorText = $_.Exception.Message
                    $copyErrorCount++

                    if ($null -ne $project) {
                        $project.CopyErrorCount++
                    }
                }
            }
            else {
                $status = "WhatIf"
            }
        }

        $csvFields = @(
            ConvertTo-CsvField $relativePath
            ConvertTo-CsvField $kind
            ConvertTo-CsvField $projectId
            ConvertTo-CsvField $projectRoot
            ConvertTo-CsvField $destinationRelativePath
            ConvertTo-CsvField $status
            ConvertTo-CsvField $errorText
        )

        $filesWriter.WriteLine([string]::Join(",", $csvFields))

        if (
            -not $NoProgress -and
            (
                ($processedRelevantFiles % 1000L) -eq 0 -or
                $processedRelevantFiles -eq $relevantFiles.Count
            )
        ) {
            $percentComplete = if ($relevantFiles.Count -gt 0) {
                [Math]::Min(
                    100,
                    [int](
                        100.0 *
                        $processedRelevantFiles /
                        $relevantFiles.Count
                    )
                )
            }
            else {
                100
            }

            $statusText = if ($Mode -eq "Extract") {
                "{0:N0}/{1:N0} files | {2:N0} copied | " +
                "{3:N0} missing | {4:N0} errors" -f @(
                    $processedRelevantFiles,
                    $relevantFiles.Count,
                    $copiedFileCount,
                    $missingFileCount,
                    $copyErrorCount
                )
            }
            else {
                "{0:N0}/{1:N0} relevant files classified" -f @(
                    $processedRelevantFiles,
                    $relevantFiles.Count
                )
            }

            Write-Progress `
                -Id 21 `
                -Activity "$Mode relevant project files" `
                -Status $statusText `
                -PercentComplete $percentComplete `
                -CurrentOperation $relativePath
        }
    }
}
finally {
    $filesWriter.Dispose()

    if (-not $NoProgress) {
        Write-Progress `
            -Id 21 `
            -Activity "$Mode relevant project files" `
            -Completed
    }
}

#endregion Extract or manifest files

#region Summary

$summary = [ordered]@{
    SchemaVersion = 1
    GeneratedUtc = [DateTime]::UtcNow.ToString("o")
    Mode = $Mode
    IndexPath = $resolvedIndexPath
    SourceRoot = $resolvedSourceRoot
    RunDirectory = $runDirectory
    ExtractionDirectory = if ($Mode -eq "Extract") {
        $extractionDirectory
    }
    else {
        $null
    }
    MinimumProjectScore = $MinimumProjectScore
    IndexedFileCount = $indexedFileCount
    IndexedDirectoryCount = $indexedDirectoryCount
    ExcludedRecordCount = $excludedRecordCount
    UserExcludedRecordCount = $userExcludedRecordCount
    InvalidRecordCount = $invalidRecordCount
    Exclusions = [ordered]@{
        Path = $resolvedExclusionsPath
        FilenameParts = @($pathExclusions.FilenameParts)
        FolderParts = @($pathExclusions.FolderParts)
    }
    RelevantFileCount = $relevantFiles.Count
    DetectedProjectCount = $projects.Count
    UnclassifiedRelevantFileCount = $unclassifiedRelevantCount
    UnclassifiedSourceFileCount = $unclassifiedSourceCount
    CopiedFileCount = $copiedFileCount
    MissingFileCount = $missingFileCount
    CopyErrorCount = $copyErrorCount
    Reports = [ordered]@{
        ProjectsCsv = $projectsCsvPath
        FilesCsv = $filesCsvPath
    }
    SecurityNotice = @(
        "Project detection and secret exclusion are heuristic."
        "Review all extracted files before publishing them."
        "Scan for credentials, private keys, API tokens and personal data."
        "Do not initialize or push repositories automatically."
    )
}

$summaryPath = Join-Path $reportDirectory "summary.json"

$summary |
    ConvertTo-Json -Depth 8 |
    Set-Content -LiteralPath $summaryPath -Encoding utf8

Write-Host ""
Write-Host "Code-project discovery completed." -ForegroundColor Green
Write-Host "Mode:                 $Mode"
Write-Host "Detected projects:    $($projects.Count)"
Write-Host "Relevant files:       $($relevantFiles.Count)"
Write-Host "Rule-excluded records: $userExcludedRecordCount"
Write-Host "Unclassified files:   $unclassifiedRelevantCount"

if ($Mode -eq "Extract") {
    Write-Host "Copied files:         $copiedFileCount"
    Write-Host "Missing source files: $missingFileCount"
    Write-Host "Copy errors:          $copyErrorCount"
}

Write-Host "Run directory:        $runDirectory"
Write-Host "Project report:       $projectsCsvPath"
Write-Host "File manifest:        $filesCsvPath"
Write-Host "Summary:              $summaryPath"
Write-Host ""
Write-Warning (
    "Review the extracted files for credentials, secrets, private keys, " +
    "personal data, licensed dependencies, and proprietary content before " +
    "publishing anything to GitHub."
)

#endregion Summary